name: librewolf-ui
description: "LibreWolf UI cleanup and browser chrome patches"
patches:
  - librewolf/ui-patches/firefox-view.patch
  - librewolf/ui-patches/handlers.patch
  - librewolf/ui-patches/hide-default-browser.patch
  - librewolf/ui-patches/remove-branding-urlbar.patch
  - librewolf/ui-patches/remove-cfrprefs.patch
  - librewolf/ui-patches/remove-organization-policy-banner.patch
